cloud:
  aws:
    region:
      static: sa-east-1
      use-default-aws-region-chain: true
    stack:
      auto: false
    credentials:
      access-key: AKIASX5FFC2JB43NBZHL
      secret-key: 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
  logging:
    level:
      com:
        amazonaws:
          internal:
            InstanceMetadataServiceResourceFetcher: error
          util:
            EC2MetadataUtils: error
